spring:
  config:
    activate:
      on-profile: qa
  kafka:
    template:
      default-topic: order-events
    producer:
      bootstrap-servers: localhost:9095,localhost:9096,localhost:9097
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer